services:
  nodejs:
    build: ./Backend/Node.js
    container_name: nodejs_backend
    ports:
      - '5555:5555'
    volumes: 
      - ./Backend/Node.js:/app
      - /app/node_modules
      - uploads:/app/uploads
    environment:
      - BACKEND_SECRET_KEY=${BACKEND_SECRET_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REACT_IP=${REACT_IP}
      - ENV=${ENV}
  react:
    build: ./Frontend/devreact
    container_name: react_frontend
    ports:
      - '5556:5556'
    volumes: 
      - ./Frontend/devreact:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_PORT=${VITE_BACKEND_PORT}
      - VITE_IP=${VITE_IP}
      - ENV=${ENV}
  database:
    image: postgres:14-alpine
    container_name: database_backend
    ports:
      - '5557:5557'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=usertest
      - PGPORT=5557
      
volumes:
  pgdata:
  uploads: