services:
  nodejs:
    build: ./Backend/Node.js
    container_name: nodejs_backend
    ports:
      - '3000:3000'
    volumes:
      - ./Backend/Node.js:/app
  react:
    build: ./Frontend/devreact
    container_name: react_frontend
    ports:
      - '4000:4000'
    volumes:
      - ./Frontend/devreact:/app
    stdin_open: true
    tty: true
  database:
    image: postgres:14-alpine
    build: ./Backend/Database
    container_name: database_backend
    ports:
      - '5432:5432'
    volumes:
      - ./Backend/Database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=testdb