services:
  nodejs:
    build: ./Backend/Node.js
    container_name: nodejs_backend
    ports:
      - '3000:3000'
    volumes:
      - ./Backend/Node.js:/app
  react:
    build: ./Frontend/devreact
    container_name: react_frontend
    ports:
      - '4000:4000'
    volumes:
      - ./Frontend/devreact:/app
    stdin_open: true
    tty: true      