services:
  nodejs:
    build: ./Backend/Node.js
    container_name: nodejs_backend
    ports:
      - '5555:5555'
    volumes: 
      - ./Backend/Node.js:/app
      - /app/node_modules
  react:
    build: ./Frontend/devreact
    container_name: react_frontend
    ports:
      - '5556:5556'
    volumes: 
      - ./Frontend/devreact:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: postgres:14-alpine
    container_name: database_backend
    ports:
      - '5557:5557'
    volumes:
      - ./Backend/Postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=testdb
      - PGPORT=5557