services:
  nodejs:
    build: ./Backend/Node.js
    container_name: nodejs_backend
    ports:
      - '5555:5555'
  react:
    build: ./Frontend/devreact
    container_name: react_frontend
    ports:
      - '5556:5546'
    stdin_open: true
    tty: true
  database:
    image: postgres:14-alpine
    container_name: database_backend
    ports:
      - '5557:5557'
    volumes:
      - ./Backend/Postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=testdb